other/missing-security-txt.bcheck

A check for a missing security.txt file according to RFC 9116.

Missing security.txt

---

other/files/configs/git-config-discovery.bcheck
other/files/configs/php-info.discovery.bcheck
other/files/configs/web-config.discovery.bcheck
other/files/npm-debug-log.bcheck
other/files/python-common.bcheck
other/files/ruby-on-rails-storage.bcheck
other/ntlm-authentication-discovery.bcheck

The following bchecks were added in this pull request:
* NTLM endpoint detection
* Git config detection
* Ruby on Rails storage.yml detection
* NPM debug log detection
* IIS web.config file detection
* PHP info file detection
These checks are unique in looking for file disclosure in that they don't just look at the site's root page but all directories discovered during a crawl. For example, if the following URL is discovered:
* https://site.acme.com/login
The checks look for git config files trailing the login directory like so:
* https://site.acme.com/login/.git/config

Added Endpoint Detection Checks

---

other/Netscaler_CitrixADC_hash_icon_detection.bcheck

This bcheck detects the netscaler and citrix adc icon on requests, which may be affected by CVE-2023-3519.

added NetScaler and citrixADC icon detection

---

other/SAP/SAP authentication bypass check.bcheck

Added a new folder in the Other directory for SAP-specific checks. This check performs a check for an authentication bypass. Which is a known and common issue for SAP applications. Advise to fix is documented in SAP Note 2258786. Which is also mentioned in the bcheck.
The authentication bypass is that normally /sap/admin/public/default.html should be requested and would result in a login screen. however index.html would directly go to the given view. Leaking inside urls, installed patches and other useful information.

Sap Authentication bypass fixed in SAP Note 2258786

---

other/takeover-s3-bucket.bcheck
other/takeover-shopify.bcheck
vulnerabilities-CVEd/CVE-2021-20323 keycloak xss.bcheck

CVE-2021-20323 + AWS S3 takeover + Shopify takeover

CVE-2021-20323 + AWS S3 takeover + Shopify takeover

---

vulnerabilities-CVEd/CVE-2023-24488 - Citrix Gateway Open Redirect and XSS.bcheck

This will avoid false positives due to the fact that some 404 status pages returns the introduced parameter encoding the "<" and ">" characters, but not the ".", so "document.cookie" appears but the rest of the payload is as introduced, "%3Cscript%3Ealert(document.cookie)%3C/script%3e". The payload should match fully in a positive case.

Update CVE-2023-24488 - Avoid false positives

---

vulnerability-classes/injection/Spring4Shell.bcheck

Added a rule to check for Spring4Shell vulnerability by targeting GET requests. Following are the conditions that I have used to validate the existence of the bug :
- status code is "400"
- response body should contain `java.lang.IllegalArgumentException` error

Added Spring4Shell.bcheck rule

---

vulnerabilities-CVEd/CVE-2022-22965-spring_data_binding_rce.bcheck
vulnerabilities-CVEd/CVE-2022-22978-spring_security_auth_bypass.bcheck

add spring CVE-2022-22965,CVE-2022-22978

add spring CVE-2022-22965,CVE-2022-22978

---

other/uuid-detected-guid-versions.bcheck

This PR introduces a new BCheck template that passively identifies and reports the use of various UUID versions within an application. The identified UUID versions include v1, v3, v4, and v5.

chore(BChecks): Add UUID Detected - GUID versions

---

other/bypass/PathSuffix_WAF_Proxy.bcheck

Adding PathSuffix-Bypass-4ProxyOrWAF.
Accessing paths blocked by proxies or WAFs by adding special suffixes.
Things like `%A0` for Nginx (https://book.hacktricks.xyz/pentesting-web/proxy-waf-protections-bypass) will not work with HTTP/2 -> I was not sure if this can be enforced by BChecks but it would be great to have this option.

Adding PathSuffix-Bypass-4ProxyOrWAF

---

other/GraphQL/grapple-get-method.bcheck

- To Find GET Method Enabled GraphQL 
- Which helps in escalating to CSRF attacks

Adding GraphQL Module

---

vulnerabilities-CVEd/CVE-2023-46805-Ivanti Auth Bypass.bcheck

CVE-2023-46805 - Ivanti Connect Secure Authentication Bypass.

---

other/Perl Jam 2 - RCE.bcheck

Create Perl Jam 2 - RCE.bcheck

---

other/GraphQL/graphql-introspection-enabled.bcheck
other/files/ds-store-exposed.bcheck
other/files/svn-exposed.bcheck

Adding the scan for Graphql Introspection Query Enabled

---

vulnerabilities-CVEd/CVE-2023-23752-Joomla-information-disclosure.bcheck

- The following image illustrates the working poc:

CVE-2023-23752 Joomla! Webservice - Users,Passwords information disclosure

---

vulnerabilities-CVEd/CVE-2018-11759-Apache mod_jk access control bypass.bcheck

This is a bcheck to detect CVE-2018-11759. This PoC can be used to test the bcheck:
https://github.com/immunIT/CVE-2018-11759

Create  CVE-2018-11759-Apache mod_jk access control bypass.bcheck

---

other/stackTrace.bcheck

Hi,
This PR propose a **bcheck** to perform the following operation: 
*Detect when a response contains a stack trace, supporting several technologies.*

Propose a bcheck to detect stack traces.

---

other/csrf_magic_backdoor.bcheck

BCheck to detect a csrf-magic backdoor.
References:
* [The backdoor code](https://web.archive.org/web/20220325023755/https://github.com/csrf-magic/csrf-magic/blob/master/csrf-magic.php)
* [Exploit Writeupe](https://www.labs.greynoise.io/grimoire/2024-02-what-is-this-old-ivanti-exploit/index.html)
* [Real-world CVE due to the backdoor](https://forums.ivanti.com/s/article/SA-2021-12-02?language=en_US)
Example output for finding:
**Overview**
**Request**
**Response**

Add bcheck for csrf-magic backdoor

---

vulnerabilities-CVEd/CVE-2011-3192-Apache DoS.bcheck

added check in response body to cut down on false positives

Update CVE-2011-3192-Apache DoS.bcheck

---

vulnerability-classes/injection/SSRFInjection.bcheck

#201 Use backticks instead of quotes

---

README.md
archived/Content-Security-Policy.bcheck

Hello,
- I originally created the "InsecureContentSecurityPolicy.bcheck" file back in **October 2023** due to Burp Suite not possessing native CSP scanner rulesets outside of referencing "frame-ancestors" for Clickjacking attacks.
- Yet as of [March 1st](https://portswigger.net/burp/releases/professional-community-2024-2-1), it appears that Burp Suite has added CSP rulesets to the native scanner.
- Meaning this BCheck has now been made mostly arbitrary.
- However, I would like to keep this BCheck as *publicly accessible* so that anyone using 2023 versions of Burp can still retain these custom rulesets.
- For example, my own company's AppSec team needs to go through a timely process when making version requests for native app tools.
- We can't even download new Burp versions nor plugins …

Added an 'Archive' directory for BChecks made outdated by updates to the Burp Suite Scanner

---

other/corsCredentialedRequestsMisconfiguration.bcheck

This PR propose a bcheck to detect invalid CORS configuration for credentialed requests.
Indeed, the server must not specify the `*` wildcard for the `Access-Control-Allow-Origin` response-header value, but must instead specify an explicit origin.
Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials
File was validated with the latest version of the checker:
Thanks in advance 😃

Propose check to detect misconfiguration for CORS credentials requested.

---

other/Javascript/malicious_polyfill_cdn.bcheck

The well-known Polyfill service CDN (polyfill.io) has been sold, and it is now serving malicious JavaScript code. Website owners using this CDN should remove the associated code from their sites immediately. For more information about this supply chain attack, visit https://sansec.io/research/polyfill-supply-chain-attack.

Create a bcheck for detecting malicious Polyfill CDN

---

other/httpMethodOverrideCapability.bcheck

Hi,
This PR propose a bcheck to check for the support for a request parameter or a request header allowing to override the HTTP method.

Check capability to override the HTTP method.

---

archived/Content-Security-Policy.bcheck
other/APIs/client_secret.bcheck

- The "client_secret.bcheck" file has been created to detect for the "client_secret", "client_id", & "refresh_token" OAuth API variables, plus variants of "api-key", within front-end files. This file is placed in the other/API folder.
- Minor update to Content-Security-Policy.bcheck to look for findings in .js & .css files.

Added client_secret.bcheck

---

vulnerabilities-CVEd/CVE-2022-22965-spring_data_binding_rce.bcheck

As discussed in #218 i have lowered the confidence level. 
Because of the lack of knowledge about this CVE and time I cannot improve the detection of this particular vulnerabilitiy. 
It seems the check could be more specific tho.

change confidence level of  CVE-2022-22965 bcheck to tentative

---

other/email/email-splitting-attack.bcheck

Fix typo in splitting attack bcheck

---

vulnerabilities-CVEd/CVE-2021-41773_CVE-2021-42013 Apache-2.4.49-50.bcheck

This Bcheck attempts to detect Apache servers vulnerable to CVE-2021-41773 and CVE-2021-42013.
I noticed something strange writing this Bcheck and I could use your help here:
According to the [Bcheck definition reference](https://portswigger.net/burp/documentation/scanner/bchecks/bcheck-definition-reference#actions), when using `report issue` the BCheck should terminate, even if there are parts of the check that have not yet run. I used it to avoid checks on 2.4.50 when the payloads for the .49 raised an issue (i.e. don't check 2.4.50 if 2.4.49 already worked), but I noticed that it keeps performing the four requests anyway. I also tried changing all to `report issue` and not using any `report issue and continue` at all, but it keeps doing the four requests. I could get the desired …

Create CVE-2021-41773_CVE-2021-42013 Apache-2.4.49-50.bcheck

---

other/uuid-detected-guid-versions.bcheck

This is a fix in reference to the following issue: #193 
I've added the configuration option to ignore the content-types related to the following image files: gif, png, jpeg, svg+xml. More can be added, in original issue request they reference it hitting on .exe files, but I could only find files with valid FP hits for the above extensions and not an .exe. If needed, I can throw that check in there as well, but I wanted to keep this as "realistic" as possible and only added checks for FP hits that I observed and could therefore test against.

Added Ignore Image Files Option to UUID BCheck

---

.gitignore

I've added this in order to ignore the default files generated by JetBrain's IDEs, such as GoLand. Normally I'd just ignore it but I've been split between several VMs & computers recently and it keeps asking me on each (haha). In the interest of keeping commits clean I am submitting this separately instead of along with a BCheck.

Added JetBrain Files to gitignore

---

vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck

- **CONTEXT**: The purpose of this request is to update the "vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck" URL.
- I wanted to create a BCheck which checks for hidden XSS fields based on: https://portswigger.net/research/exploiting-xss-in-hidden-inputs-and-meta-tags
- The current version of this bcheck only checks if ```<input>``` has ```type="hidden"``` as its very first attribute.
- The current version of this bcheck also does not consider hidden fields via ```style="display: none;"```
- I've also provided additions to the detail & remediation text which provides an easy example for how users should test Hidden Input findings for XSS.
**Ask**: As this is a significant update to a pre-existing bcheck file, please let me know what the correct syntax is for …

Updated the "Hidden Input Field Detection at Response Level (Passive)" Finding

---

vulnerability-classes/injection/ExtendedSSRFInjection.bcheck

Contains checks that may detect certain scenarios where valid URLs might need a different path or scheme to achieve OOB SSRF.

Added OOB SSRF Checks for HTTP + DNS

---

other/bypass/403 & 401 Header Bypass via IP.bcheck

Added a check to see if 403/401 status code responses could be bypassed using header modifications that use IP-related payloads.

Created 403 & 401 Header Bypass via IP.bcheck

---

vulnerabilities-CVEd/CVE-2025-29927-Next-js-middleware-bypass.bcheck

A bcheck for the recent Next.js Bypass identified as CVE-2025-29927. Used https://slcyber.io/assetnote-security-research-center/doing-the-due-diligence-analysing-the-next-js-middleware-bypass-cve-2025-29927/ for creating this. 
This is my first contribution so all feedback is welcomed.

Added bcheck for Next.js Bypass CVE-2025-29927

---

other/tokens/jwt-hmac-alg-detected.bcheck

This is in response to a request on the Burp discord server for a bcheck that alerts on a JWT using HMAC.
This bcheck looks for JWTs using HMAC in the following formats:
```
{"alg":"HS256","typ":"JWT"}
{"typ":"JWT","alg":"HS256"}
{"alg":"HS384","typ":"JWT"}
{"typ":"JWT","alg":"HS384"}
{"alg":"HS512","typ":"JWT"}
{"typ":"JWT","alg":"HS512"}
{"alg":"HS256"}
{"alg":"HS384"}
{"alg":"HS512"}
```
I tried to extract JWTs and base64 decode them to retrieve the algorithm, but I did not find this functionality in bchecks. If that exists, please point me to further documentation and I can try to rewrite this to be more accurate.

Added bcheck to detect JWTs that utilize HMAC algorithms

---

other/HTTP Methods/CONNECT_port_scan.bcheck
vulnerabilities-CVEd/CVE-2025-30208_Vite_dev_server.bcheck

added 2 BChecks - CVE-2025-30208_Vite_dev_server and CONNECT_port_scan

---

other/springboot/Springboot heapdump actuator.bcheck

adding missing check for Springboot heapdump actuator

Create Springboot heapdump actuator.bcheck
